--- %YAML:1.0

title    : Roll
brief    : Ruby Object-Oriented Library Ledger
author   : Thomas Sawyer
email    : transfire@gmail.com
homepage : "http://roll.rubyforge.org"
created  : 2006-12-10
summary  :
  Roll is a library manager for Ruby. Code repositories
  can be made visible to Ruby just by setting an
  environment variable. Rolls effectively trivializes
  Ruby package management.

formats: [ zip ]  # tar.gz, gem ]
exclude: [ doc, dev, pkg ]

recommend:
  - [ box ,">= 0.3.0"]

