---

publish:
  project   : roll
  source    : doc
  username  : transami

changes:
  history   : 'log/history.txt'
  changes   : 'CHANGES'

changelog:
  txtlog    : 'log/changelog.txt'
  xmllog    : 'doc/log/changelog.xml'
