#sow: {}

basicstats:
  service: BasicStats

notes:
  service: Notes

rdoc:
  service  : RDoc
  template : jamis
  inline   : true
  output   : doc/rdoc

ridoc:
  service  : RiDoc
  output   : doc/ri

#testunit:
#  service : TestUnit

zip:
  service  : Zip

rubyforge:
  service  : RubyForge
  unixname : roll
  groupid  : 1004

